[package]
name = "bevy_piet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_piet_render = { path = "bevy_piet_render" }

[dev-dependencies]
bevy = {version ="0.9" }
pollster = "0.2.5"

[[example]]
name = "render"
path = "example/render_to_png.rs"

[package.metadata.example.text2d]
name = "Render to Png"
description = "Generete Png file with render"
category = "2D Rendering"